version: "3.8"

services:
  # Next.js Frontend
  app:
    image: aurora1010/marketorix:${FRONTEND_TAG:-latest}
    container_name: marketorix-nextjs
    restart: unless-stopped
    networks:
      - n8n_default
    labels:
      # Enable Traefik for this service
      - "traefik.enable=true"

      # --- Define a single, shared "service" that both routers will point to ---
      - "traefik.http.services.marketorix-strapi-service.loadbalancer.server.port=1337"

      # --- ROUTER 1: For you, the user. Catches `/strapi` and strips it. ---
      - "traefik.http.routers.marketorix-strapi-user.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`/strapi`)"
      - "traefik.http.routers.marketorix-strapi-user.entrypoints=websecure"
      - "traefik.http.routers.marketorix-strapi-user.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.marketorix-strapi-user.service=marketorix-strapi-service"

      # --- ROUTER 2: The "fix-it" router. Catches the broken `/admin` asset links. ---
      - "traefik.http.routers.marketorix-strapi-fix.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`/admin`)"
      - "traefik.http.routers.marketorix-strapi-fix.entrypoints=websecure"
      - "traefik.http.routers.marketorix-strapi-fix.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.marketorix-strapi-fix.service=marketorix-strapi-service"

      # --- Define the stripPrefix middleware that Router 1 will use ---
      - "traefik.http.middlewares.strapi-stripprefix.stripprefix.prefixes=/strapi"

      # --- Apply the middleware ONLY to the user-facing router ---
      - "traefik.http.routers.marketorix-strapi-user.middlewares=strapi-stripprefix@docker"

  # Strapi Backend
  strapi:
    image: aurora1010/my-blog-strapi-v2:latest-prod # Make sure this points to your new image name
    container_name: marketorix-strapi
    restart: unless-stopped
    env_file: .env
    volumes:
      - strapi-uploads:/opt/app/public/uploads
    networks:
      - n8n_default
      - default
    # This is now correctly uncommented to ensure proper startup order
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.marketorix-strapi.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`/strapi`)"
      - "traefik.http.routers.marketorix-strapi.entrypoints=websecure"
      - "traefik.http.routers.marketorix-strapi.tls.certresolver=mytlschallenge"
      - "traefik.http.services.marketorix-strapi.loadbalancer.server.port=1337"

      # Define the stripPrefix middleware
      - "traefik.http.middlewares.strapi-stripprefix.stripprefix.prefixes=/strapi"

      # Apply the middleware to the router
      - "traefik.http.routers.marketorix-strapi.middlewares=strapi-stripprefix@docker"


      # --- Apply the middleware ONLY to the user-facing router ---
      - "traefik.http.routers.marketorix-strapi-user.middlewares=strapi-stripprefix@docker"

  # Strapi Database
  db:
    container_name: marketorix-db
    image: postgres:15-alpine
    restart: unless-stopped
    env_file: .env
    volumes:
      - strapi-data:/var/lib/postgresql/data
    networks:
      - default

# Volumes are now correctly declared
volumes:
  strapi-data:
  strapi-uploads:

networks:
  n8n_default:
    external: true
  default:
    driver: bridge